In [ ]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
Profile=pd.read_excel("ProfileLinkdin.xlsx")

In [ ]:
Profile.head()

,error,baseUrl,timestamp,linkedinProfile,email,description,headline,location,imgUrl,firstName,...,mail,jobDescription2,schoolDescription,schoolDescription2,connectionsCount,twitter,website,facebookUrl,connectedOn,phoneNumber
0,Not a LinkedIn Profile URL,profileUrl,2022-02-07T08:26:52.486Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,https://www.linkedin.com/in/ghada-ben-aicha-91...,2022-02-07T08:27:00.094Z,https://www.linkedin.com/in/ghada-ben-aicha-91...,NaN,Infos\n- I am a Enterprise systems engineering...,Étudiante en mastère de recherche '' enterpris...,"Tunis, Tunis, Tunisie",https://media-exp1.licdn.com/dms/image/C4E03AQ...,Ghada,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,https://www.linkedin.com/in/houssem-arfaoui-10...,2022-02-07T08:27:11.431Z,https://www.linkedin.com/in/houssem-arfaoui-10...,NaN,Diplômé d’un Master professionnel en électroni...,Technicien production chez SAH Lilas,"Tunis, Tunis, Tunisie",https://media-exp1.licdn.com/dms/image/C4E35AQ...,Houssem,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,https://www.linkedin.com/in/dhikra-ben-mahmoud...,2022-02-07T08:27:20.970Z,https://www.linkedin.com/in/dhikra-ben-mahmoud...,NaN,NaN,Business intelligence student,"Kalaât El Andalous, Ariana, Tunisie",https://media-exp1.licdn.com/dms/image/C5603AQ...,dhikra,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,https://www.linkedin.com/in/eya-smati-03b462195/,2022-02-07T08:27:34.497Z,https://www.linkedin.com/in/eya-smati-03b462195/,eyasmati13@gmail.com,NaN,Data Science Project Instructor chez Coursera,"Tunis, Tunisie",https://media-exp1.licdn.com/dms/image/C4E03AQ...,Eya,...,eyasmati13@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
Profile.tail()

,error,baseUrl,timestamp,linkedinProfile,email,description,headline,location,imgUrl,firstName,...,mail,jobDescription2,schoolDescription,schoolDescription2,connectionsCount,twitter,website,facebookUrl,connectedOn,phoneNumber
368,NaN,https://www.linkedin.com/in/rym-ben-amara/,2022-02-16T11:44:03.878Z,https://www.linkedin.com/in/rym-ben-amara/,NaN,NaN,Software QA Tester chez Rhenus Logistics,"Nabeul, Tunisie",https://media-exp1.licdn.com/dms/image/C4D03AQ...,Rym,...,NaN,Développement d'une plugin WordPress,NaN,NaN,738.0,NaN,NaN,NaN,NaN,NaN
369,NaN,https://www.linkedin.com/in/mahmoud-ben-ayed-9...,2022-02-16T11:44:16.045Z,https://www.linkedin.com/in/mahmoud-ben-ayed-9...,NaN,NaN,Étudiant à Institut supérieur d'informatique\n...,"Tunis, Tunisie",https://media-exp1.licdn.com/dms/image/C4D03AQ...,Mahmoud,...,NaN,NaN,NaN,NaN,478.0,NaN,NaN,NaN,NaN,NaN
370,NaN,https://www.linkedin.com/in/geovanni-awana-a61...,2022-02-16T11:44:27.194Z,https://www.linkedin.com/in/geovanni-awana-a61...,NaN,NaN,Étudiant(e) à Ecole Supérieure Privée d'Ingéni...,"Tunis, Tunisie",https://media-exp1.licdn.com/dms/image/C4D03AQ...,Geovanni,...,NaN,NaN,NaN,NaN,101.0,NaN,NaN,NaN,NaN,NaN
371,NaN,https://www.linkedin.com/in/rihab-touati-43a37...,2022-02-16T11:44:39.924Z,https://www.linkedin.com/in/rihab-touati-43a37...,NaN,Je suis passionne par le web et les nouvelles ...,Développeur Systèmes Embarqués/IOT/ Data Scien...,"Plage Soliman, Nabeul, Tunisie",https://media-exp1.licdn.com/dms/image/C5603AQ...,Rihab,...,NaN,etude et realisation d'un moniteur d'énergie \...,Activités et associations : -GOOGLE DEVELOPER ...,NaN,4182.0,NaN,NaN,NaN,NaN,NaN
372,NaN,https://www.linkedin.com/in/hanen-makni-6b6763...,2022-02-16T11:44:51.842Z,https://www.linkedin.com/in/hanen-makni-6b6763...,NaN,NaN,HR & Finance Director at VIRTUALDEV GROUP,"Tunis, Tunis, Tunisie",https://media-exp1.licdn.com/dms/image/C5603AQ...,Hanen,...,NaN,NaN,NaN,NaN,502.0,NaN,NaN,NaN,NaN,NaN

In [ ]:
Profile['jobDateRange']

0                                          NaN
1              févr. 2021 - juin 2021 · 5 mois
2             août 2021 - aujourd’hui · 7 mois
3                                          NaN
4            sept. 2021 - aujourd’hui · 6 mois
                        ...
368    févr. 2020 - aujourd’hui · 2 ans 1 mois
369          janv. 2022 - aujourd’hui · 2 mois
370                                        NaN
371            févr. 2020 - août 2020 · 7 mois
372     déc. 2013 - aujourd’hui · 8 ans 3 mois
Name: jobDateRange, Length: 373, dtype: object

In [ ]:
Profile['jobDateRange'].fillna("vide",inplace=True)

In [ ]:
experience=[]

def extractChaine():
  for i in range(0,len(Profile['jobDateRange'])):
    pos = Profile['jobDateRange'][i].rfind("·")
    expExtract = Profile['jobDateRange'][i][pos+1:]
    experience.append(expExtract)
    #print(experience)
    #print([float(s) for s in re.findall(r'-?\d+\.?\d*', expExtract)])
  return experience



exp1 = extractChaine()

In [ ]:
Profile['jobDateRange2'].fillna("vide",inplace=True)
Profile['jobDateRange2']

0                                        vide
1                         juil. 2019 · 1 mois
2            févr. 2018 - juil. 2018 · 6 mois
3                                        vide
4      sept. 2020 - aujourd’hui · 1 an 6 mois
                        ...
368           sept. 2019 - déc. 2019 · 4 mois
369                                      vide
370                                      vide
371           juin 2019 - juil. 2019 · 2 mois
372     nov. 2010 - févr. 2013 · 2 ans 4 mois
Name: jobDateRange2, Length: 373, dtype: object

In [ ]:
experience2=[]

def extractChaine():
  for i in range(0,len(Profile['jobDateRange2'])):
    pos = Profile['jobDateRange2'][i].rfind("·")
    expExtract = Profile['jobDateRange2'][i][pos+1:]
    experience2.append(expExtract)
    #print(experience2)
    #print([float(s) for s in re.findall(r'-?\d+\.?\d*', expExtract)])
  return experience2



exp2 = extractChaine()

new_df=Profile.assign(experience1=exp1,experience2=exp2)

new_df

,error,baseUrl,timestamp,linkedinProfile,email,description,headline,location,imgUrl,firstName,...,schoolDescription,schoolDescription2,connectionsCount,twitter,website,facebookUrl,connectedOn,phoneNumber,experience1,experience2
0,Not a LinkedIn Profile URL,profileUrl,2022-02-07T08:26:52.486Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,vide,vide
1,NaN,https://www.linkedin.com/in/ghada-ben-aicha-91...,2022-02-07T08:27:00.094Z,https://www.linkedin.com/in/ghada-ben-aicha-91...,NaN,Infos\n- I am a Enterprise systems engineering...,Étudiante en mastère de recherche '' enterpris...,"Tunis, Tunis, Tunisie",https://media-exp1.licdn.com/dms/image/C4E03AQ...,Ghada,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5 mois,1 mois
2,NaN,https://www.linkedin.com/in/houssem-arfaoui-10...,2022-02-07T08:27:11.431Z,https://www.linkedin.com/in/houssem-arfaoui-10...,NaN,Diplômé d’un Master professionnel en électroni...,Technicien production chez SAH Lilas,"Tunis, Tunis, Tunisie",https://media-exp1.licdn.com/dms/image/C4E35AQ...,Houssem,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7 mois,6 mois
3,NaN,https://www.linkedin.com/in/dhikra-ben-mahmoud...,2022-02-07T08:27:20.970Z,https://www.linkedin.com/in/dhikra-ben-mahmoud...,NaN,NaN,Business intelligence student,"Kalaât El Andalous, Ariana, Tunisie",https://media-exp1.licdn.com/dms/image/C5603AQ...,dhikra,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,vide,vide
4,NaN,https://www.linkedin.com/in/eya-smati-03b462195/,2022-02-07T08:27:34.497Z,https://www.linkedin.com/in/eya-smati-03b462195/,eyasmati13@gmail.com,NaN,Data Science Project Instructor chez Coursera,"Tunis, Tunisie",https://media-exp1.licdn.com/dms/image/C4E03AQ...,Eya,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6 mois,1 an 6 mois
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
368,NaN,https://www.linkedin.com/in/rym-ben-amara/,2022-02-16T11:44:03.878Z,https://www.linkedin.com/in/rym-ben-amara/,NaN,NaN,Software QA Tester chez Rhenus Logistics,"Nabeul, Tunisie",https://media-exp1.licdn.com/dms/image/C4D03AQ...,Rym,...,NaN,NaN,738.0,NaN,NaN,NaN,NaN,NaN,2 ans 1 mois,4 mois
369,NaN,https://www.linkedin.com/in/mahmoud-ben-ayed-9...,2022-02-16T11:44:16.045Z,https://www.linkedin.com/in/mahmoud-ben-ayed-9...,NaN,NaN,Étudiant à Institut supérieur d'informatique\n...,"Tunis, Tunisie",https://media-exp1.licdn.com/dms/image/C4D03AQ...,Mahmoud,...,NaN,NaN,478.0,NaN,NaN,NaN,NaN,NaN,2 mois,vide
370,NaN,https://www.linkedin.com/in/geovanni-awana-a61...,2022-02-16T11:44:27.194Z,https://www.linkedin.com/in/geovanni-awana-a61...,NaN,NaN,Étudiant(e) à Ecole Supérieure Privée d'Ingéni...,"Tunis, Tunisie",https://media-exp1.licdn.com/dms/image/C4D03AQ...,Geovanni,...,NaN,NaN,101.0,NaN,NaN,NaN,NaN,NaN,vide,vide
371,NaN,https://www.linkedin.com/in/rihab-touati-43a37...,2022-02-16T11:44:39.924Z,https://www.linkedin.com/in/rihab-touati-43a37...,NaN,Je suis passionne par le web et les nouvelles ...,Développeur Systèmes Embarqués/IOT/ Data Scien...,"Plage Soliman, Nabeul, Tunisie",https://media-exp1.licdn.com/dms/image/C5603AQ...,Rihab,...,Activités et associations : -GOOGLE DEVELOPER ...,NaN,4182.0,NaN,NaN,NaN,NaN,NaN,7 mois,2 mois
372,NaN,https://www.linkedin.com/in/hanen-makni-6b6763...,2022-02-16T11:44:51.842Z,https://www.linkedin.com/in/hanen-makni-6b6763...,NaN,NaN,HR & Finance Director at VIRTUALDEV GROUP,"Tunis, Tunis, Tunisie",https://media-exp1.licdn.com/dms/image/C5603AQ...,Hanen,...,NaN,NaN,502.0,NaN,NaN,NaN,NaN,NaN,8 ans 3 mois,2 ans 4 mois

In [ ]:
del new_df['jobDateRange']
del new_df['jobDateRange2']

In [ ]:
new_df

,error,baseUrl,timestamp,linkedinProfile,email,description,headline,location,imgUrl,firstName,...,schoolDescription,schoolDescription2,connectionsCount,twitter,website,facebookUrl,connectedOn,phoneNumber,experience1,experience2
0,Not a LinkedIn Profile URL,profileUrl,2022-02-07T08:26:52.486Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,vide,vide
1,NaN,https://www.linkedin.com/in/ghada-ben-aicha-91...,2022-02-07T08:27:00.094Z,https://www.linkedin.com/in/ghada-ben-aicha-91...,NaN,Infos\n- I am a Enterprise systems engineering...,Étudiante en mastère de recherche '' enterpris...,"Tunis, Tunis, Tunisie",https://media-exp1.licdn.com/dms/image/C4E03AQ...,Ghada,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5 mois,1 mois
2,NaN,https://www.linkedin.com/in/houssem-arfaoui-10...,2022-02-07T08:27:11.431Z,https://www.linkedin.com/in/houssem-arfaoui-10...,NaN,Diplômé d’un Master professionnel en électroni...,Technicien production chez SAH Lilas,"Tunis, Tunis, Tunisie",https://media-exp1.licdn.com/dms/image/C4E35AQ...,Houssem,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7 mois,6 mois
3,NaN,https://www.linkedin.com/in/dhikra-ben-mahmoud...,2022-02-07T08:27:20.970Z,https://www.linkedin.com/in/dhikra-ben-mahmoud...,NaN,NaN,Business intelligence student,"Kalaât El Andalous, Ariana, Tunisie",https://media-exp1.licdn.com/dms/image/C5603AQ...,dhikra,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,vide,vide
4,NaN,https://www.linkedin.com/in/eya-smati-03b462195/,2022-02-07T08:27:34.497Z,https://www.linkedin.com/in/eya-smati-03b462195/,eyasmati13@gmail.com,NaN,Data Science Project Instructor chez Coursera,"Tunis, Tunisie",https://media-exp1.licdn.com/dms/image/C4E03AQ...,Eya,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6 mois,1 an 6 mois
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
368,NaN,https://www.linkedin.com/in/rym-ben-amara/,2022-02-16T11:44:03.878Z,https://www.linkedin.com/in/rym-ben-amara/,NaN,NaN,Software QA Tester chez Rhenus Logistics,"Nabeul, Tunisie",https://media-exp1.licdn.com/dms/image/C4D03AQ...,Rym,...,NaN,NaN,738.0,NaN,NaN,NaN,NaN,NaN,2 ans 1 mois,4 mois
369,NaN,https://www.linkedin.com/in/mahmoud-ben-ayed-9...,2022-02-16T11:44:16.045Z,https://www.linkedin.com/in/mahmoud-ben-ayed-9...,NaN,NaN,Étudiant à Institut supérieur d'informatique\n...,"Tunis, Tunisie",https://media-exp1.licdn.com/dms/image/C4D03AQ...,Mahmoud,...,NaN,NaN,478.0,NaN,NaN,NaN,NaN,NaN,2 mois,vide
370,NaN,https://www.linkedin.com/in/geovanni-awana-a61...,2022-02-16T11:44:27.194Z,https://www.linkedin.com/in/geovanni-awana-a61...,NaN,NaN,Étudiant(e) à Ecole Supérieure Privée d'Ingéni...,"Tunis, Tunisie",https://media-exp1.licdn.com/dms/image/C4D03AQ...,Geovanni,...,NaN,NaN,101.0,NaN,NaN,NaN,NaN,NaN,vide,vide
371,NaN,https://www.linkedin.com/in/rihab-touati-43a37...,2022-02-16T11:44:39.924Z,https://www.linkedin.com/in/rihab-touati-43a37...,NaN,Je suis passionne par le web et les nouvelles ...,Développeur Systèmes Embarqués/IOT/ Data Scien...,"Plage Soliman, Nabeul, Tunisie",https://media-exp1.licdn.com/dms/image/C5603AQ...,Rihab,...,Activités et associations : -GOOGLE DEVELOPER ...,NaN,4182.0,NaN,NaN,NaN,NaN,NaN,7 mois,2 mois
372,NaN,https://www.linkedin.com/in/hanen-makni-6b6763...,2022-02-16T11:44:51.842Z,https://www.linkedin.com/in/hanen-makni-6b6763...,NaN,NaN,HR & Finance Director at VIRTUALDEV GROUP,"Tunis, Tunis, Tunisie",https://media-exp1.licdn.com/dms/image/C5603AQ...,Hanen,...,NaN,NaN,502.0,NaN,NaN,NaN,NaN,NaN,8 ans 3 mois,2 ans 4 mois

In [ ]:
periodeL=[]
periodeLL=[]

for j in range(len(new_df['experience1'])):
  periode=[int(s) for s in re.findall(r'-?\d+\.?\d*', new_df['experience1'][j])]
  periodeL.append(periode)
#print(periodeL)

for j in range(len(new_df['experience2'])):
  periode=[int(s) for s in re.findall(r'-?\d+\.?\d*', new_df['experience2'][j])]
  periodeLL.append(periode)
#print(periodeLL)


Profileee=new_df.assign(periode=periodeL,periode2=periodeLL)
Profileee

,error,baseUrl,timestamp,linkedinProfile,email,description,headline,location,imgUrl,firstName,...,connectionsCount,twitter,website,facebookUrl,connectedOn,phoneNumber,experience1,experience2,periode,periode2
0,Not a LinkedIn Profile URL,profileUrl,2022-02-07T08:26:52.486Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,vide,vide,[],[]
1,NaN,https://www.linkedin.com/in/ghada-ben-aicha-91...,2022-02-07T08:27:00.094Z,https://www.linkedin.com/in/ghada-ben-aicha-91...,NaN,Infos\n- I am a Enterprise systems engineering...,Étudiante en mastère de recherche '' enterpris...,"Tunis, Tunis, Tunisie",https://media-exp1.licdn.com/dms/image/C4E03AQ...,Ghada,...,NaN,NaN,NaN,NaN,NaN,NaN,5 mois,1 mois,[5],[1]
2,NaN,https://www.linkedin.com/in/houssem-arfaoui-10...,2022-02-07T08:27:11.431Z,https://www.linkedin.com/in/houssem-arfaoui-10...,NaN,Diplômé d’un Master professionnel en électroni...,Technicien production chez SAH Lilas,"Tunis, Tunis, Tunisie",https://media-exp1.licdn.com/dms/image/C4E35AQ...,Houssem,...,NaN,NaN,NaN,NaN,NaN,NaN,7 mois,6 mois,[7],[6]
3,NaN,https://www.linkedin.com/in/dhikra-ben-mahmoud...,2022-02-07T08:27:20.970Z,https://www.linkedin.com/in/dhikra-ben-mahmoud...,NaN,NaN,Business intelligence student,"Kalaât El Andalous, Ariana, Tunisie",https://media-exp1.licdn.com/dms/image/C5603AQ...,dhikra,...,NaN,NaN,NaN,NaN,NaN,NaN,vide,vide,[],[]
4,NaN,https://www.linkedin.com/in/eya-smati-03b462195/,2022-02-07T08:27:34.497Z,https://www.linkedin.com/in/eya-smati-03b462195/,eyasmati13@gmail.com,NaN,Data Science Project Instructor chez Coursera,"Tunis, Tunisie",https://media-exp1.licdn.com/dms/image/C4E03AQ...,Eya,...,NaN,NaN,NaN,NaN,NaN,NaN,6 mois,1 an 6 mois,[6],"[1, 6]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
368,NaN,https://www.linkedin.com/in/rym-ben-amara/,2022-02-16T11:44:03.878Z,https://www.linkedin.com/in/rym-ben-amara/,NaN,NaN,Software QA Tester chez Rhenus Logistics,"Nabeul, Tunisie",https://media-exp1.licdn.com/dms/image/C4D03AQ...,Rym,...,738.0,NaN,NaN,NaN,NaN,NaN,2 ans 1 mois,4 mois,"[2, 1]",[4]
369,NaN,https://www.linkedin.com/in/mahmoud-ben-ayed-9...,2022-02-16T11:44:16.045Z,https://www.linkedin.com/in/mahmoud-ben-ayed-9...,NaN,NaN,Étudiant à Institut supérieur d'informatique\n...,"Tunis, Tunisie",https://media-exp1.licdn.com/dms/image/C4D03AQ...,Mahmoud,...,478.0,NaN,NaN,NaN,NaN,NaN,2 mois,vide,[2],[]
370,NaN,https://www.linkedin.com/in/geovanni-awana-a61...,2022-02-16T11:44:27.194Z,https://www.linkedin.com/in/geovanni-awana-a61...,NaN,NaN,Étudiant(e) à Ecole Supérieure Privée d'Ingéni...,"Tunis, Tunisie",https://media-exp1.licdn.com/dms/image/C4D03AQ...,Geovanni,...,101.0,NaN,NaN,NaN,NaN,NaN,vide,vide,[],[]
371,NaN,https://www.linkedin.com/in/rihab-touati-43a37...,2022-02-16T11:44:39.924Z,https://www.linkedin.com/in/rihab-touati-43a37...,NaN,Je suis passionne par le web et les nouvelles ...,Développeur Systèmes Embarqués/IOT/ Data Scien...,"Plage Soliman, Nabeul, Tunisie",https://media-exp1.licdn.com/dms/image/C5603AQ...,Rihab,...,4182.0,NaN,NaN,NaN,NaN,NaN,7 mois,2 mois,[7],[2]
372,NaN,https://www.linkedin.com/in/hanen-makni-6b6763...,2022-02-16T11:44:51.842Z,https://www.linkedin.com/in/hanen-makni-6b6763...,NaN,NaN,HR & Finance Director at VIRTUALDEV GROUP,"Tunis, Tunis, Tunisie",https://media-exp1.licdn.com/dms/image/C5603AQ...,Hanen,...,502.0,NaN,NaN,NaN,NaN,NaN,8 ans 3 mois,2 ans 4 mois,"[8, 3]","[2, 4]"

In [ ]:
type(Profileee['periode'][3])

list

In [ ]:
calcul = 0
l = [] 
for i in Profileee['periode']:
  if (len(i) > 1) :
    calcul = i[0] * 12 + i[1]
  elif ((len(i) == 1)):
    calcul = i[0]
  else :
   calcul = 0
  
  l.append(calcul)

calcul2 = 0
l2 = [] 
for i in Profileeee['periode2']:
  if (len(i) > 1) :
    calcul = i[0] * 12 + i[1]
  elif ((len(i) == 1)):
    calcul = i[0]
  else :
   calcul = 0
  
  l2.append(calcul)

df_Profile = Profileee.assign(res=l,res2=l2)

df_Profile

,error,baseUrl,timestamp,linkedinProfile,email,description,headline,location,imgUrl,firstName,...,website,facebookUrl,connectedOn,phoneNumber,experience1,experience2,periode,periode2,res,res2
0,Not a LinkedIn Profile URL,profileUrl,2022-02-07T08:26:52.486Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,vide,vide,[],[],0,0
1,NaN,https://www.linkedin.com/in/ghada-ben-aicha-91...,2022-02-07T08:27:00.094Z,https://www.linkedin.com/in/ghada-ben-aicha-91...,NaN,Infos\n- I am a Enterprise systems engineering...,Étudiante en mastère de recherche '' enterpris...,"Tunis, Tunis, Tunisie",https://media-exp1.licdn.com/dms/image/C4E03AQ...,Ghada,...,NaN,NaN,NaN,NaN,5 mois,1 mois,[5],[1],5,1
2,NaN,https://www.linkedin.com/in/houssem-arfaoui-10...,2022-02-07T08:27:11.431Z,https://www.linkedin.com/in/houssem-arfaoui-10...,NaN,Diplômé d’un Master professionnel en électroni...,Technicien production chez SAH Lilas,"Tunis, Tunis, Tunisie",https://media-exp1.licdn.com/dms/image/C4E35AQ...,Houssem,...,NaN,NaN,NaN,NaN,7 mois,6 mois,[7],[6],7,6
3,NaN,https://www.linkedin.com/in/dhikra-ben-mahmoud...,2022-02-07T08:27:20.970Z,https://www.linkedin.com/in/dhikra-ben-mahmoud...,NaN,NaN,Business intelligence student,"Kalaât El Andalous, Ariana, Tunisie",https://media-exp1.licdn.com/dms/image/C5603AQ...,dhikra,...,NaN,NaN,NaN,NaN,vide,vide,[],[],0,0
4,NaN,https://www.linkedin.com/in/eya-smati-03b462195/,2022-02-07T08:27:34.497Z,https://www.linkedin.com/in/eya-smati-03b462195/,eyasmati13@gmail.com,NaN,Data Science Project Instructor chez Coursera,"Tunis, Tunisie",https://media-exp1.licdn.com/dms/image/C4E03AQ...,Eya,...,NaN,NaN,NaN,NaN,6 mois,1 an 6 mois,[6],"[1, 6]",6,18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
368,NaN,https://www.linkedin.com/in/rym-ben-amara/,2022-02-16T11:44:03.878Z,https://www.linkedin.com/in/rym-ben-amara/,NaN,NaN,Software QA Tester chez Rhenus Logistics,"Nabeul, Tunisie",https://media-exp1.licdn.com/dms/image/C4D03AQ...,Rym,...,NaN,NaN,NaN,NaN,2 ans 1 mois,4 mois,"[2, 1]",[4],25,4
369,NaN,https://www.linkedin.com/in/mahmoud-ben-ayed-9...,2022-02-16T11:44:16.045Z,https://www.linkedin.com/in/mahmoud-ben-ayed-9...,NaN,NaN,Étudiant à Institut supérieur d'informatique\n...,"Tunis, Tunisie",https://media-exp1.licdn.com/dms/image/C4D03AQ...,Mahmoud,...,NaN,NaN,NaN,NaN,2 mois,vide,[2],[],2,0
370,NaN,https://www.linkedin.com/in/geovanni-awana-a61...,2022-02-16T11:44:27.194Z,https://www.linkedin.com/in/geovanni-awana-a61...,NaN,NaN,Étudiant(e) à Ecole Supérieure Privée d'Ingéni...,"Tunis, Tunisie",https://media-exp1.licdn.com/dms/image/C4D03AQ...,Geovanni,...,NaN,NaN,NaN,NaN,vide,vide,[],[],0,0
371,NaN,https://www.linkedin.com/in/rihab-touati-43a37...,2022-02-16T11:44:39.924Z,https://www.linkedin.com/in/rihab-touati-43a37...,NaN,Je suis passionne par le web et les nouvelles ...,Développeur Systèmes Embarqués/IOT/ Data Scien...,"Plage Soliman, Nabeul, Tunisie",https://media-exp1.licdn.com/dms/image/C5603AQ...,Rihab,...,NaN,NaN,NaN,NaN,7 mois,2 mois,[7],[2],7,2
372,NaN,https://www.linkedin.com/in/hanen-makni-6b6763...,2022-02-16T11:44:51.842Z,https://www.linkedin.com/in/hanen-makni-6b6763...,NaN,NaN,HR & Finance Director at VIRTUALDEV GROUP,"Tunis, Tunis, Tunisie",https://media-exp1.licdn.com/dms/image/C5603AQ...,Hanen,...,NaN,NaN,NaN,NaN,8 ans 3 mois,2 ans 4 mois,"[8, 3]","[2, 4]",99,28

In [ ]:
resultat = df_Profile['res'] + df_Profile['res2']
df_Prof = df_Profile.assign(experience = resultat)
df_Prof.rename(columns = {'experience':'experience (en mois)'}, inplace = True)
df_Prof

,error,baseUrl,timestamp,linkedinProfile,email,description,headline,location,imgUrl,firstName,...,facebookUrl,connectedOn,phoneNumber,experience1,experience2,periode,periode2,res,res2,experience (en mois)
0,Not a LinkedIn Profile URL,profileUrl,2022-02-07T08:26:52.486Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,vide,vide,[],[],0,0,0
1,NaN,https://www.linkedin.com/in/ghada-ben-aicha-91...,2022-02-07T08:27:00.094Z,https://www.linkedin.com/in/ghada-ben-aicha-91...,NaN,Infos\n- I am a Enterprise systems engineering...,Étudiante en mastère de recherche '' enterpris...,"Tunis, Tunis, Tunisie",https://media-exp1.licdn.com/dms/image/C4E03AQ...,Ghada,...,NaN,NaN,NaN,5 mois,1 mois,[5],[1],5,1,6
2,NaN,https://www.linkedin.com/in/houssem-arfaoui-10...,2022-02-07T08:27:11.431Z,https://www.linkedin.com/in/houssem-arfaoui-10...,NaN,Diplômé d’un Master professionnel en électroni...,Technicien production chez SAH Lilas,"Tunis, Tunis, Tunisie",https://media-exp1.licdn.com/dms/image/C4E35AQ...,Houssem,...,NaN,NaN,NaN,7 mois,6 mois,[7],[6],7,6,13
3,NaN,https://www.linkedin.com/in/dhikra-ben-mahmoud...,2022-02-07T08:27:20.970Z,https://www.linkedin.com/in/dhikra-ben-mahmoud...,NaN,NaN,Business intelligence student,"Kalaât El Andalous, Ariana, Tunisie",https://media-exp1.licdn.com/dms/image/C5603AQ...,dhikra,...,NaN,NaN,NaN,vide,vide,[],[],0,0,0
4,NaN,https://www.linkedin.com/in/eya-smati-03b462195/,2022-02-07T08:27:34.497Z,https://www.linkedin.com/in/eya-smati-03b462195/,eyasmati13@gmail.com,NaN,Data Science Project Instructor chez Coursera,"Tunis, Tunisie",https://media-exp1.licdn.com/dms/image/C4E03AQ...,Eya,...,NaN,NaN,NaN,6 mois,1 an 6 mois,[6],"[1, 6]",6,18,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
368,NaN,https://www.linkedin.com/in/rym-ben-amara/,2022-02-16T11:44:03.878Z,https://www.linkedin.com/in/rym-ben-amara/,NaN,NaN,Software QA Tester chez Rhenus Logistics,"Nabeul, Tunisie",https://media-exp1.licdn.com/dms/image/C4D03AQ...,Rym,...,NaN,NaN,NaN,2 ans 1 mois,4 mois,"[2, 1]",[4],25,4,29
369,NaN,https://www.linkedin.com/in/mahmoud-ben-ayed-9...,2022-02-16T11:44:16.045Z,https://www.linkedin.com/in/mahmoud-ben-ayed-9...,NaN,NaN,Étudiant à Institut supérieur d'informatique\n...,"Tunis, Tunisie",https://media-exp1.licdn.com/dms/image/C4D03AQ...,Mahmoud,...,NaN,NaN,NaN,2 mois,vide,[2],[],2,0,2
370,NaN,https://www.linkedin.com/in/geovanni-awana-a61...,2022-02-16T11:44:27.194Z,https://www.linkedin.com/in/geovanni-awana-a61...,NaN,NaN,Étudiant(e) à Ecole Supérieure Privée d'Ingéni...,"Tunis, Tunisie",https://media-exp1.licdn.com/dms/image/C4D03AQ...,Geovanni,...,NaN,NaN,NaN,vide,vide,[],[],0,0,0
371,NaN,https://www.linkedin.com/in/rihab-touati-43a37...,2022-02-16T11:44:39.924Z,https://www.linkedin.com/in/rihab-touati-43a37...,NaN,Je suis passionne par le web et les nouvelles ...,Développeur Systèmes Embarqués/IOT/ Data Scien...,"Plage Soliman, Nabeul, Tunisie",https://media-exp1.licdn.com/dms/image/C5603AQ...,Rihab,...,NaN,NaN,NaN,7 mois,2 mois,[7],[2],7,2,9
372,NaN,https://www.linkedin.com/in/hanen-makni-6b6763...,2022-02-16T11:44:51.842Z,https://www.linkedin.com/in/hanen-makni-6b6763...,NaN,NaN,HR & Finance Director at VIRTUALDEV GROUP,"Tunis, Tunis, Tunisie",https://media-exp1.licdn.com/dms/image/C5603AQ...,Hanen,...,NaN,NaN,NaN,8 ans 3 mois,2 ans 4 mois,"[8, 3]","[2, 4]",99,28,127

In [ ]:
del df_Prof['periode']
del df_Prof['periode2']
del df_Prof['res']
del df_Prof['res2']

In [ ]:
df_Prof

,error,baseUrl,timestamp,linkedinProfile,email,description,headline,location,imgUrl,firstName,...,schoolDescription2,connectionsCount,twitter,website,facebookUrl,connectedOn,phoneNumber,experience1,experience2,experience (en mois)
0,Not a LinkedIn Profile URL,profileUrl,2022-02-07T08:26:52.486Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,vide,vide,0
1,NaN,https://www.linkedin.com/in/ghada-ben-aicha-91...,2022-02-07T08:27:00.094Z,https://www.linkedin.com/in/ghada-ben-aicha-91...,NaN,Infos\n- I am a Enterprise systems engineering...,Étudiante en mastère de recherche '' enterpris...,"Tunis, Tunis, Tunisie",https://media-exp1.licdn.com/dms/image/C4E03AQ...,Ghada,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5 mois,1 mois,6
2,NaN,https://www.linkedin.com/in/houssem-arfaoui-10...,2022-02-07T08:27:11.431Z,https://www.linkedin.com/in/houssem-arfaoui-10...,NaN,Diplômé d’un Master professionnel en électroni...,Technicien production chez SAH Lilas,"Tunis, Tunis, Tunisie",https://media-exp1.licdn.com/dms/image/C4E35AQ...,Houssem,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7 mois,6 mois,13
3,NaN,https://www.linkedin.com/in/dhikra-ben-mahmoud...,2022-02-07T08:27:20.970Z,https://www.linkedin.com/in/dhikra-ben-mahmoud...,NaN,NaN,Business intelligence student,"Kalaât El Andalous, Ariana, Tunisie",https://media-exp1.licdn.com/dms/image/C5603AQ...,dhikra,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,vide,vide,0
4,NaN,https://www.linkedin.com/in/eya-smati-03b462195/,2022-02-07T08:27:34.497Z,https://www.linkedin.com/in/eya-smati-03b462195/,eyasmati13@gmail.com,NaN,Data Science Project Instructor chez Coursera,"Tunis, Tunisie",https://media-exp1.licdn.com/dms/image/C4E03AQ...,Eya,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6 mois,1 an 6 mois,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
368,NaN,https://www.linkedin.com/in/rym-ben-amara/,2022-02-16T11:44:03.878Z,https://www.linkedin.com/in/rym-ben-amara/,NaN,NaN,Software QA Tester chez Rhenus Logistics,"Nabeul, Tunisie",https://media-exp1.licdn.com/dms/image/C4D03AQ...,Rym,...,NaN,738.0,NaN,NaN,NaN,NaN,NaN,2 ans 1 mois,4 mois,29
369,NaN,https://www.linkedin.com/in/mahmoud-ben-ayed-9...,2022-02-16T11:44:16.045Z,https://www.linkedin.com/in/mahmoud-ben-ayed-9...,NaN,NaN,Étudiant à Institut supérieur d'informatique\n...,"Tunis, Tunisie",https://media-exp1.licdn.com/dms/image/C4D03AQ...,Mahmoud,...,NaN,478.0,NaN,NaN,NaN,NaN,NaN,2 mois,vide,2
370,NaN,https://www.linkedin.com/in/geovanni-awana-a61...,2022-02-16T11:44:27.194Z,https://www.linkedin.com/in/geovanni-awana-a61...,NaN,NaN,Étudiant(e) à Ecole Supérieure Privée d'Ingéni...,"Tunis, Tunisie",https://media-exp1.licdn.com/dms/image/C4D03AQ...,Geovanni,...,NaN,101.0,NaN,NaN,NaN,NaN,NaN,vide,vide,0
371,NaN,https://www.linkedin.com/in/rihab-touati-43a37...,2022-02-16T11:44:39.924Z,https://www.linkedin.com/in/rihab-touati-43a37...,NaN,Je suis passionne par le web et les nouvelles ...,Développeur Systèmes Embarqués/IOT/ Data Scien...,"Plage Soliman, Nabeul, Tunisie",https://media-exp1.licdn.com/dms/image/C5603AQ...,Rihab,...,NaN,4182.0,NaN,NaN,NaN,NaN,NaN,7 mois,2 mois,9
372,NaN,https://www.linkedin.com/in/hanen-makni-6b6763...,2022-02-16T11:44:51.842Z,https://www.linkedin.com/in/hanen-makni-6b6763...,NaN,NaN,HR & Finance Director at VIRTUALDEV GROUP,"Tunis, Tunis, Tunisie",https://media-exp1.licdn.com/dms/image/C5603AQ...,Hanen,...,NaN,502.0,NaN,NaN,NaN,NaN,NaN,8 ans 3 mois,2 ans 4 mois,127

In [ ]:
#@title
#import re

#def wordsStartsWith(string,c):
  #regex = r"\b(" + c + r"\s+)\b"

  #return re.findall(regex,string)

In [ ]:
#@title
#def dateExperience():
  #for i in range(len(Profile['jobDateRange'])):
    #date = wordsStartsWith(Profile['jobDateRange'].values[i],'·')
    #print(date)
  #return date
  
#date = dateExperience()
#date